### ISSUE TITLE
As a user, I want the vacuum to optimally navigate to efficiently use it's battery

### ISSUE THREAD

**Issue by dipen8699** [dipen8699/Clean-Sweap#21]

**Comment by sherelyn-saceda** [comment]
@wasikhalid Write Acceptance Criteria

**Comment by wasikhalid** [comment]
*Acceptance Criteria*

- Efficiently Navigation Pathfinding
  Minimize unnecessary backtracking or overlap 

- Obstacle detection and avoidance 
 Vacuum bot must detect and avoid obstacles without requiring external intervention

- Smart Charging Behavior 
 When battery level drops to below a predefined threshold, bot must return to its charging station autonomously. 

After charging, the vacuum must resume cleaning from the last position to avoid redundant cleaning
